#!/usr/bin/env python3
"""
Packs the Entra Self-Service canvas app into an .msapp you can open in Power Apps Studio
(File > Open > Browse), instead of pasting the five screens by hand.

    python3 build.py          # (re)generate ../screens/*.pa.yaml first, if you changed the design
    PAC=/path/to/pac python3 build_msapp.py

Input:  ../screens/*.pa.yaml (paste format), ../App.Formulas.fx, ../App.OnStart.fx,
        ../Screens.OnVisible.fx, ../msapp-base/ (a clean, empty tablet app skeleton)
Output: ../src/   Power Apps source-code layout (Src/*.pa.yaml + EntraSelfService.msapr)
        ../dist/EntraSelfService.msapp

The .msapp carries every control and formula. It deliberately has NO data sources:
SharePoint data sources embed each list's GUID and schema from your tenant, so you add
EntraRequests, EntraCatalogApps, EntraCatalogGroups and Office 365 Users after opening it
(docs/03 section 3.0). Studio compiles the YAML when the app is first opened.
"""
from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import uuid
import zipfile
from pathlib import Path

import yaml

PA = Path(__file__).resolve().parent.parent
BASE = PA / "msapp-base"
SRC = PA / "src"
DIST = PA / "dist"
APP_NAME = "Entra Self-Service"
FILE_STEM = "EntraSelfService"
SCREENS = ["scrHome", "scrNewApp", "scrNewGroup", "scrAddGroup", "scrAppChange", "scrMyRequests"]
APP_ID = "6f0c3a1e-2b7d-4e55-9a10-5c3e0e1d0a01"   # stable, so re-opening keeps the same app identity

# Control versions as used by current Studio builds (doc version 1.349 sample apps).
VERSIONS = {
    "Label": "2.5.1", "Classic/Button": "2.2.0", "Classic/TextInput": "2.3.2", "Classic/DropDown": "2.3.1",
    "Classic/ComboBox": "2.4.0", "Classic/CheckBox": "2.1.0", "Classic/Radio": "2.3.0", "Classic/Toggle": "2.1.0",
    "Classic/Icon": "2.5.0", "Rectangle": "2.3.0", "HtmlViewer": "2.1.0", "Gallery": "2.15.0", "GroupContainer": "1.5.0",
}

HEADER_COMMENT = """# ************************************************************************************************
# Generated by powerapps/tools/build_msapp.py from the paste-format screens. Open the packed
# .msapp in Power Apps Studio; edit the generator (tools/build.py) rather than this file.
# ************************************************************************************************
"""


class Literal(str):
    pass


def literal_representer(dumper, data):
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")


class Dumper(yaml.SafeDumper):
    pass


Dumper.add_representer(Literal, literal_representer)


def formula(text: str) -> str:
    """A Power Fx property value: '=' + formula; multi-line formulas as YAML block literals."""
    text = text.strip()
    return Literal("=" + text) if "\n" in text else "=" + text


def strip_header_comments(fx: str) -> str:
    """Drop the leading // comment block of an .fx file (instructions for the paste route)."""
    lines = fx.splitlines()
    while lines and (lines[0].startswith("//") or not lines[0].strip()):
        lines.pop(0)
    return "\n".join(lines).strip()


def on_visible_by_screen() -> dict[str, str]:
    text = (PA / "Screens.OnVisible.fx").read_text()
    parts = re.split(r"^// ===== (\w+)\.OnVisible\s*$", text, flags=re.M)
    out = {}
    for i in range(1, len(parts), 2):
        body = "\n".join(l for l in parts[i + 1].splitlines() if not l.lstrip().startswith("//")).strip()
        out[parts[i]] = body
    return out


def add_versions(node):
    if isinstance(node, list):
        for x in node:
            add_versions(x)
    elif isinstance(node, dict):
        if "Control" in node and "@" not in str(node["Control"]):
            v = VERSIONS.get(node["Control"])
            if not v:
                raise SystemExit(f"no version known for control type {node['Control']}")
            node["Control"] = f"{node['Control']}@{v}"
        for x in node.values():
            add_versions(x)


def keep_literals(node):
    """Re-wrap multi-line formulas as block literals so the YAML stays readable."""
    if isinstance(node, list):
        return [keep_literals(x) for x in node]
    if isinstance(node, dict):
        return {k: keep_literals(v) for k, v in node.items()}
    if isinstance(node, str) and "\n" in node:
        return Literal(node)
    return node


def dump(doc) -> str:
    return HEADER_COMMENT + yaml.dump(keep_literals(doc), Dumper=Dumper, sort_keys=False, allow_unicode=True, width=10_000)


def write_sources():
    if SRC.exists():
        shutil.rmtree(SRC)
    (SRC / "Src").mkdir(parents=True)

    app = {"App": {"Properties": {
        "Formulas": formula(strip_header_comments((PA / "App.Formulas.fx").read_text())),
        "OnStart": formula(strip_header_comments((PA / "App.OnStart.fx").read_text())),
    }}}
    (SRC / "Src" / "App.pa.yaml").write_text(dump(app))

    visible = on_visible_by_screen()
    for name in SCREENS:
        children = yaml.safe_load((PA / "screens" / f"{name}.pa.yaml").read_text())
        add_versions(children)
        props = {"Fill": "=gTheme.Bg"}
        if visible.get(name):
            props["OnVisible"] = formula(visible[name])
        doc = {"Screens": {name: {"Properties": props, "Children": children}}}
        (SRC / "Src" / f"{name}.pa.yaml").write_text(dump(doc))

    (SRC / "Src" / "_EditorState.pa.yaml").write_text(dump({"EditorState": {"ScreensOrder": SCREENS}}))


def write_msapr():
    flags = json.loads((BASE / "app-preview-flags.json").read_text())
    properties = {
        "Author": "", "Name": APP_NAME, "Id": APP_ID, "FileID": APP_ID,
        "LocalConnectionReferences": "{}", "LocalDatabaseReferences": "", "LibraryDependencies": "[]",
        "AppPreviewFlagsMap": flags,
        "DocumentLayoutWidth": 1366, "DocumentLayoutHeight": 768, "DocumentLayoutOrientation": "landscape",
        "DocumentLayoutScaleToFit": True, "DocumentLayoutMaintainAspectRatio": True, "DocumentLayoutLockOrientation": False,
        "ShowStatusBar": False, "AppCopilotSchemaName": "", "OriginatingVersion": "1.349",
        "DocumentAppType": "DesktopOrTablet", "DocumentType": "App", "AppCreationSource": "AppFromScratch",
        "AppDescription": "Entra ID self-service: register applications, expose APIs, app roles, role assignments, enterprise apps and security groups, with manager and Entra ID team approval.",
        "ManualOfflineProfileId": "", "DefaultConnectedDataSourceMaxGetRowsCount": 2000,
        "ContainsThirdPartyPcfControls": False, "ParserErrorCount": 0, "BindingErrorCount": 0,
        "ConnectionString": "", "EnableInstrumentation": False, "ControlCount": {},
    }
    publish = {"AppName": APP_NAME, "BackgroundColor": "RGBA(15,108,189,1)", "PublishTarget": "player", "LogoFileName": "",
               "IconColor": "RGBA(255,255,255,1)", "IconName": "Shield", "PublishResourcesLocally": False,
               "PublishDataLocally": False, "UserLocale": "en-US"}
    files = {
        "msapr-header.json": (BASE / "msapr-header.json").read_bytes(),
        "msapp/Header.json": (BASE / "msapp" / "Header.json").read_bytes(),
        "msapp/Properties.json": json.dumps(properties).encode(),
        "msapp/Controls/1.json": (BASE / "msapp" / "Controls" / "1.json").read_bytes(),
        "msapp/References/Themes.json": (BASE / "msapp" / "References" / "Themes.json").read_bytes(),
        "msapp/References/ModernThemes.json": (BASE / "msapp" / "References" / "ModernThemes.json").read_bytes(),
        "msapp/References/Templates.json": (BASE / "msapp" / "References" / "Templates.json").read_bytes(),
        "msapp/References/DataSources.json": json.dumps({"DataSources": []}).encode(),
        "msapp/References/Resources.json": json.dumps({"Resources": []}).encode(),
        "msapp/Resources/PublishInfo.json": json.dumps(publish).encode(),
    }
    with zipfile.ZipFile(SRC / f"{FILE_STEM}.msapr", "w", zipfile.ZIP_DEFLATED) as z:
        for name, data in files.items():
            z.writestr(name, data)


def validate_schema():
    """Validate every Src/*.pa.yaml against Microsoft's published pa.yaml v3 schema."""
    try:
        import jsonschema
    except ImportError:
        print("jsonschema not installed: schema validation skipped")
        return
    schema = yaml.safe_load((BASE / "pa.schema.yaml").read_text())
    validator = jsonschema.Draft7Validator(schema)
    problems = 0
    for f in sorted((SRC / "Src").glob("*.pa.yaml")):
        doc = yaml.safe_load(f.read_text())
        for err in validator.iter_errors(doc):
            problems += 1
            print(f"  schema: {f.name}: {'/'.join(map(str, err.absolute_path))}: {err.message[:160]}")
    print(f"schema validation: {problems} problem(s) in {len(list((SRC / 'Src').glob('*.pa.yaml')))} files")
    if problems:
        sys.exit(1)


def pack():
    pac = os.environ.get("PAC") or shutil.which("pac")
    if not pac:
        print("pac not found: set PAC=/path/to/pac to pack the .msapp")
        return
    DIST.mkdir(exist_ok=True)
    out = DIST / f"{FILE_STEM}.msapp"
    subprocess.run([pac, "canvas", "pack", "--sources", str(SRC), "--msapp", str(out), "--layout", "SourceCode",
                    "--overwrite"], check=True)
    print(f"packed {out}")


if __name__ == "__main__":
    write_sources()
    write_msapr()
    validate_schema()
    pack()
